# Generated by Django 6.0.8 on 2026-08-31 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DivisaSeguida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simbolo', models.CharField(max_length=20)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisas_seguidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['orden', 'simbolo'],
                'unique_together': {('usuario', 'simbolo')},
            },
        ),
        migrations.CreateModel(
            name='TableroSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simbolo', models.CharField(db_index=True, max_length=20)),
                ('timeframe', models.CharField(db_index=True, max_length=6)),
                ('datos', models.JSONField()),
                ('calculado_en', models.DateTimeField(auto_now=True)),
                ('error', models.TextField(blank=True, default='')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['usuario', 'calculado_en'], name='dashboard_t_usuario_287f2a_idx')],
                'unique_together': {('usuario', 'simbolo', 'timeframe')},
            },
        ),
        migrations.CreateModel(
            name='TemporalidadSeguida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(max_length=6)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporalidades_seguidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['orden', 'timeframe'],
                'unique_together': {('usuario', 'timeframe')},
            },
        ),
    ]
