# Generated by Django 6.0.8 on 2026-09-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='pref_auto_pivot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='pref_corto',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='pref_kalman',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='pref_largo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='pref_mediano',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='pref_relleno',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='pref_tablero_canales',
            field=models.BooleanField(default=False),
        ),
    ]
