# Generated by Django 6.0.8 on 2026-09-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_perfilusuario_pref_auto_pivot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='watchlist_generacion',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
