# Generated by Django 6.0.8 on 2026-09-07 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_perfilusuario_watchlist_generacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='pref_kn_signals',
            field=models.BooleanField(default=False),
        ),
    ]
