# Generated by Django 6.0.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_perfilusuario_pref_kn_signals'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='pref_sr_avanzado',
            field=models.BooleanField(default=False),
        ),
    ]
