"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carga variables desde .env si existe (en desarrollo local). En un
# servidor real, las variables de entorno se setean directo en el
# sistema/contenedor y esta llamada simplemente no encuentra nada que
# cargar — no rompe nada si el archivo no está.
load_dotenv(BASE_DIR / ".env")


# SECURITY WARNING: keep the secret key used in production secret!
# En desarrollo, si no hay .env, cae a una clave insegura de placeholder
# — funciona para correr local, pero NUNCA se debe desplegar así: Django
# tira un warning bien visible (django.core.checks) si detecta que se
# está usando esta clave de fallback.
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-CAMBIAR-ESTA-CLAVE-antes-de-produccion-ver-.env.example",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "True").strip().lower() in ("1", "true", "yes")

ALLOWED_HOSTS = [h.strip() for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Apps propias
    'accounts',
    'core',
    'drawings',
    'dashboard',
    'chartview',

    # Celery (tareas periódicas + resultados)
    'django_celery_beat',
    'django_celery_results',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True


# ── Login / logout ──
LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'dashboard:home'
LOGOUT_REDIRECT_URL = 'accounts:login'


# ── Celery: recalcula el tablero de cada usuario cada 5 minutos en
# segundo plano (django-celery-beat) — el navegador solo LEE el último
# snapshot ya calculado (barato), nunca recalcula al pedir la página.
#
# Broker por defecto: FILESYSTEM (carpetas broker/in, broker/out,
# broker/processed en vez de un servidor Redis aparte) — cero instalación
# adicional, ideal para correr en una sola PC sin Docker/servicios extra.
# Si en algún momento se necesita algo más robusto (varios workers, otra
# máquina), basta con cambiar CELERY_BROKER_URL en el .env a
# "redis://localhost:6379/0" y correr Redis — el resto del código no
# cambia. ──
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "filesystem://")
if CELERY_BROKER_URL == "filesystem://":
    _BROKER_DIR = BASE_DIR / "broker"
    for _sub in ("in", "out", "processed"):
        (_BROKER_DIR / _sub).mkdir(parents=True, exist_ok=True)
    CELERY_BROKER_TRANSPORT_OPTIONS = {
        "data_folder_in": str(_BROKER_DIR / "out"),   # sí, "in" apunta a la carpeta "out" —
        "data_folder_out": str(_BROKER_DIR / "out"),  # es el truco estándar para un solo host:
        "data_folder_processed": str(_BROKER_DIR / "processed"),
    }
CELERY_RESULT_BACKEND = 'django-db'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
