# Generated by Django 6.0.8 on 2026-08-31 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dibujo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simbolo', models.CharField(db_index=True, max_length=20)),
                ('timeframe', models.CharField(db_index=True, max_length=6)),
                ('tipo', models.CharField(choices=[('trendline', 'Línea de tendencia'), ('hline', 'Línea horizontal'), ('fib', 'Retroceso de Fibonacci'), ('brush', 'Dibujo libre'), ('text', 'Texto')], max_length=20)),
                ('datos', models.JSONField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dibujos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['creado'],
                'indexes': [models.Index(fields=['usuario', 'simbolo', 'timeframe'], name='drawings_di_usuario_600505_idx')],
            },
        ),
    ]
